# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-14 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodeads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.TextField()),
                ('pres', models.TextField()),
            ],
        ),
    ]
