# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-14 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodeads', '0002_graf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culeba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('lon', models.TextField()),
                ('lat', models.TextField()),
                ('date_time', models.TextField()),
                ('temp_max', models.TextField()),
                ('temp_min', models.TextField()),
                ('wind', models.TextField()),
                ('cloud', models.TextField()),
                ('pressure', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
