# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-14 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodeads', '0003_culeba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culeba',
            name='cloud',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='culeba',
            name='date_time',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='culeba',
            name='description',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='culeba',
            name='lat',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='culeba',
            name='lon',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='culeba',
            name='name',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='culeba',
            name='pressure',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='culeba',
            name='temp_max',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='culeba',
            name='temp_min',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='culeba',
            name='wind',
            field=models.CharField(max_length=140),
        ),
    ]
