# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-14 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodeads', '0004_auto_20161214_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='culeba',
            name='date',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
        migrations.AddField(
            model_name='culeba',
            name='time',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
        migrations.AlterField(
            model_name='culeba',
            name='date_time',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
    ]
