# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-14 22:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodeads', '0005_auto_20161215_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culeba',
            name='date_time',
        ),
    ]
