# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-14 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodeads', '0006_remove_culeba_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culeba',
            name='date',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='culeba',
            name='time',
            field=models.CharField(max_length=140),
        ),
    ]
